WIP: Update plotting slices and add polar projection view
PrincetonUniversity/athena pull request #394
Opened 2021-09-21 20:46 UTC by kurtsansom

## Prerequisite checklist

- [ ] My code follows the Athena++ [Style Guide](https://github.com/PrincetonUniversity/athena/wiki/Style-Guide)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation in the [Wiki](https://github.com/PrincetonUniversity/athena/wiki) accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Please review the [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md) file for detailed guidelines.

## Description
- Newer versions of h5py read strings as by strings and require being encoded to enable/disable options, prefer utf-8 over ascii
- Stream plots from single precision data fail without recasting grid limits, so recast cell coordinates into uniform data
- prefer explicit objects over `plt.` usage with figures, axes, etc. 
- plots assume rectangular grid, add polar projection for cylindrical plots

Commits should have been split up but want to get feedback to determine if these changes are useful upstream

## Testing and validation
Ad hoc testing on current data, appears to work for cylindrical slice 

## To-do

- [ ] currently the figure size is hard-coded to `(12, 12)`  and could be made a variable with a default

2021-09-21 22:01 UTC, c-white commented
I think these are generally useful.

Quickly scanning them, I think ascii -> utf-8 is probably fine, though I'm pretty certain Athena will never use non-ascii characters when writing that string to file. @felker, since you put that in originally, is there a preference? In any event, this should be done consistently with decodings in `athena_read.py`.

2021-09-21 22:05 UTC, c-white commented
One other thing to consider: Having a polar plot is definitely useful, but there should probably be a way for users to turn it off as well. It's sometimes helpful to see the data in its raw form without manipulating it into a more physical shape, and if `plot_slice.py` doesn't do that, no other script will.

Alternatively, we could do something like spherical coordinates does: `plot_slice.py` just plots raw slices, while a new `plot_cylindrical.py` makes more physically meaningful plots. This might be overkill for cylindrical coordinates, though.

2021-09-22 02:26 UTC, felker requested changes
I agree with using `fig`, `ax`, etc. instead of `plt` for the matplotlib calls.

The decode calls should be to `ascii`, not `utf-8`.

https://support.hdfgroup.org/HDF5/doc/RM/RM_H5T.html#Datatype-SetCset
> By default, HDF5 creates object and attribute names with ASCII character encoding. An object or attribute creation property list setting is required to create object names with UTF-8 characters. This uses the function H5Pset_char_encoding, which sets the character encoding used for object and attribute names.

We do not specify UTF in the 3x string attributes written in https://github.com/PrincetonUniversity/athena/blob/master/src/outputs/athena_hdf5.cpp, so they are ASCII encoded. See, e.g.:
```
➜  athena git:(master) h5dump -A  kh-shear-lecoanet.out2.00027.athdf
HDF5 "kh-shear-lecoanet.out2.00027.athdf" {
GROUP "/" {
   ATTRIBUTE "Coordinates" {
      DATATYPE  H5T_STRING {
         STRSIZE 21;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "cartesian"
      }
   }
   ATTRIBUTE "DatasetNames" {
      DATATYPE  H5T_STRING {
         STRSIZE 21;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): "prim"
      }
...
   ATTRIBUTE "VariableNames" {
      DATATYPE  H5T_STRING {
         STRSIZE 21;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SIMPLE { ( 6 ) / ( 6 ) }
      DATA {
      (0): "rho", "press", "vel1", "vel2", "vel3", "r0"
      }
   }
```

2021-09-22 02:26 UTC, felker commented on vis/python/athena_read.py
> -    raw_data_ascii = raw_data.decode('ascii', 'replace')
VTK binaries are ASCII encoded, not UTF-8.

2021-11-23 17:28 UTC, felker commented
@kurtsansom did you see my feedback on this? Can we update and merge soon?

2021-11-30 22:21 UTC, kurtsansom commented
@felker I am behind on some other projects at the moment. I can close for now or someone else can pick it up.

2021-12-01 05:19 UTC, merged